#!/bin/sh
### BEGIN INIT INFO
# Provides:          dnsbl-server
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DNSBL Server
# Description:       Multi-zone DNSBL server with real-time forwarding
### END INIT INFO

NAME=dnsbl-server
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log
USER=dnsbl

[ -f /etc/default/$NAME ] && . /etc/default/$NAME

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting $NAME"
    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --chuid $USER --exec $DAEMON -- $DAEMON_OPTS > $LOGFILE 2>&1 & then
        log_end_msg 0
    else
        log_end_msg 1
    fi
    ;;
  stop)
    log_daemon_msg "Stopping $NAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    log_end_msg $?
    rm -f $PIDFILE
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME
    ;;
  restart|force-reload)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|force-reload}"
    exit 1
    ;;
esac

exit 0

